version: "3.9"
services:
  mvn-repo:
    build: ./mvn-repo
    networks:
      backend-network:

  nginx-proxy:
    build: ./nginx-proxy
    networks:
      backend-network:
      builds-network:
    depends_on:
      - mvn-repo
    ports:
    - "443:443"
    - "80:80" # only for debug

networks:
  backend-network:
  builds-network: