version: "3.9"
services:
  mvn-repo:
    build: ./mvn-repo
    image: communitybuild3/mvn-repo
    networks:
      backend-network:

  nginx-proxy:
    build:
      context: ./nginx-proxy
      args:
        MAVEN_CERT_PASS: maven_cert_pass # TODO: Replace for production use
    image: communitybuild3/nginx-proxy
    networks:
      backend-network:
      builds-network:
    depends_on:
      - mvn-repo
    ports:
    - "443:443"
    - "80:80" # only for debug

networks:
  backend-network:
    name: backend-network
  builds-network:
    name: builds-network