apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: community-build
spec:
  version: 7.13.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: community-build
spec:
  version: 7.13.0
  count: 1
  elasticsearchRef:
    name: community-build
    