jobs:
- script: |
    pipelineScript = new File('/var/jenkins_home/seeds/runDaily.groovy').text
    requiredProjects = new File('/var/jenkins_home/build-configs/required-projects.txt').text
    replacedProjects = new File('/var/jenkins_home/build-configs/replaced-projects.txt').text
    pipelineJob('runDaily') {
      definition {
        cps {
          script(pipelineScript)
          sandbox()
        }
      }
      parameters {
        separator {
          name("COMPILER")
          sectionHeader("Compiler")
          separatorStyle("")
          sectionHeaderStyle("")
        }
        stringParam("publishedScalaVersion", null, "(Optional, for debugging purposes mainly): An already published version of the compiler to be used instead of building one from sources, e.g. '3.1.1-RC1-bin-20210904-a82a1a6-NIGHTLY'. When specified, the remaining parameters from this section are ignored")
        stringParam("scalaRepoUrl", "https://github.com/lampepfl/dotty.git")
        stringParam("scalaRepoBranch", "master")
        separator {
          name("BUILD_PLAN")
          sectionHeader("Build plan")
          separatorStyle("")
          sectionHeaderStyle("")
        }
        stringParam("precomputedBuildPlan", null, "(Optional, for debugging purposes mainly): The build plan (in JSON format) to be used instead of computing the plan dynamically. When specified, the remaining parameters from this section are ignored")
        stringParam("scalaBinaryVersionSeries", "3.x", "Scala binary version following Scaladex API convention used for detecting projects to be built")
        stringParam("minStarsCount", "100", "Minimal number of start on GitHub required to include a project into the build plan")
        stringParam("maxProjectsCount", "40", "Maximal number of projects to include into the build plan")
        stringParam("requiredProjects", requiredProjects, "Comma-sepatrated list of projects that have to be included into the build plan (using GitHub coordinates), e.g. 'typelevel/cats,scalaz/scalaz'")
        textParam("replacedProjects", replacedProjects, "Mapping specifying which projects should be replaced by their forks. Each line in format: <original_org>/<original_name> <new_org>/<new_name> [<new_branch_name>], e.g. 'scalaz/scalaz dotty-staging/scalaz' or 'milessabin/shapeless dotty-staging/shapeless shapeless-3-staging'. Lines which are empty or start with # are ignored")
        separator {
          name("GENERAL")
          sectionHeader("General")
          separatorStyle("")
          sectionHeaderStyle("")
        }
        stringParam("mvnRepoBaseUrl", "http://mvn-repo:8081/maven2")
        stringParam("elasticSearchUrl", "https://community-build-es-http:9200")
      }
    }
