jobs:
- script: |
    pipelineScript = new File('/var/jenkins_home/seeds/runDaily.groovy').text
    pipelineJob('runDaily') {
      definition {
        cps {
          script(pipelineScript)
          sandbox()
        }
      }
    }
