server:
  port: 8081
  servlet:
    context-path: /maven2
maven:
  multiRepo: false
  redirectUrl: https://repo1.maven.org/maven2 #https://repo1.maven.org.fake/maven2
  scala:
    targetVersion: 3.0.0-RC3